[package]
authors = ["Edward Yang <edward.yang6771@gmail.com>"]
name = "physics-sim-gtk"
version = "0.1.0"

[dependencies]
cairo-rs = "0.1.0"
gdk = "0.5.0"
gdk-sys = "0.3.2"
gtk = "0.1.0"
time = "0.1.35"

[dependencies.physics-sim]
git = "https://github.com/efyang/physics-sim"
